/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A configuration interface for Languages */
export interface I18nConfig {
  /**
   * directory relative or absolute where locales are located.
   * @type {string} path
   */
  directory: string
  /**
   * A list of available locales.
   * @type {string[]} locales
   */
  locales: Array<string>
  /**
   * fallback language.
   * @type {string} fallback
   */
  fallback?: string
  /**
   * default language, defaults to the fallback language if not specified.
   * @type {string} [default]
   */
  default?: string
  /**
   * A flag indicating whether to preload locales on initialization.
   * @type {boolean} [preload]
   */
  preload?: boolean
}
/** Manages languages and store in cache */
export class I18n {
  /**
   * @type {string} fallback use if current locale fail
   * @readonly
   */
  readonly fallback: string
  /**
   * @type {string} locale is the current language
   * @readonly
   */
  readonly locale: string
  /**
   * @type {string} directory relative or absolute where locales are located.
   * @readonly
   */
  readonly directory: string
  /**
   * @type {string[]} locales - A list of available locales, if specified.
   * @readonly
   */
  readonly locales: Array<string>
  /**
   * Create a new Languages class from the config provide
   * @param {I18nConfig} options - Options for class I18n
   */
  constructor(options: I18nConfig)
}
