[workspace]
members = [
  "packages/allocator",
  "packages/humanize",
  "packages/i18n",
  "packages/security",
]
resolver = '2'

[profile.release]
lto = true
strip = "symbols"
codegen-units = 1
overflow-checks = false
