[package]
name = "allocator"
version = "0.1.0"
edition = "2021"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.5"

[target.'cfg(target_env = "msvc")'.dependencies]
mimalloc = "0.1"
