/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Humanize a byte size into a string.
 *
 * @param {number} bytes
 * @returns {string} a string representation of that size in a human-readable format.
*/
export declare function humanizeBytes(bytes: number): string
/**
 * Humanize a duration in milliseconds to a string.
 *
 * @param {number} ms - the duration in milliseconds.
 * @param {number} [maxUnits=7] - the maximum number of units to display (default is 7).
 * @param {boolean} [short=false] - Whether to use short abbreviations (default is false)
 * @returns {string} a human-readable string representation of the duration.
*/
export declare function humanizeDuration(ms: number, maxUnits?: number | undefined | null, short?: boolean | undefined | null): string
