/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function humanizeBytes(bytes: number): string
/**
 * humanizeDuration function takes `milliseconds`, maximum units and short format as input.
 *
 * @param {number} ms - input milliseconds
 * @param {number} [maxUnits=7] - maximum units to display (min: 1, max: 7, default: 7)
 * @param {boolean} [short=false] - use short format (default: false)
 * @returns {string} a human-readable duration string
 */
export function humanizeDuration(ms: number, maxUnits?: number | undefined | null, short?: boolean | undefined | null): string
